version: "3.7"
services:
  puff-server:
    image: elixir:1.8.2-otp-22
    build:
      context: ../puff_server
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ../puff_server:/workspace
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: sleep infinity
  puff-cli:
    build:
      context: ../puffcli
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ../puffcli:/workspace
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    command: sleep infinity

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./devenv/data/postgres:/var/lib/postgres/data


