version: 2.1

executors:
  elixir:
    parameters:
      app:
        type: string
        default: ""
    docker:
      - image: circleci/elixir:1.9.1
        environment:
          MIX_ENV: test
          MINIO_HOST: "127.0.0.1"
          POSTGRES_HOST: "127.0.0.1"
      - image: circleci/rust:1.35.0
      - image: minio/minio:latest
        environment:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: minio123
        command: ["server", "/data"]
      - image: circleci/postgres:11.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: buff_server_test
    working_directory: ~/app/<< parameters.app >>
    environment:
      MIX_ENV: test

commands:
  fast-checkout:
    steps:
      - attach_workspace:
          at: /home/circleci
  restore_plts:
    steps:
      - run:
          name: "ELIXIR_VERSION.lock"
          command: echo "${ELIXIR_VERSION}" > ELIXIR_VERSION.lock
      - run:
          name: "OTP_VERSION.lock"
          command: echo "${OTP_VERSION}" > OTP_VERSION.lock
      - restore_cache:
          keys:
            - v1-plt-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.lock" }}
            - v1-plt-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.exs" }}
            - v1-plt-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
  save_plts:
    steps:
      - run:
          name: "ELIXIR_VERSION.lock"
          command: echo "${ELIXIR_VERSION}" > ELIXIR_VERSION.lock
      - run:
          name: "OTP_VERSION.lock"
          command: echo "${OTP_VERSION}" > OTP_VERSION.lock
      - save_cache:
          key: v1-plt-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.lock" }}
          paths:
            - deps
            - _build
            - ~/.mix
            - priv/plts
      - save_cache:
          key: v1-plt-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.exs" }}
          paths:
            - deps
            - _build
            - ~/.mix
            - priv/plts
      - save_cache:
          key: v1-plt-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - deps
            - _build
            - ~/.mix
            - priv/plts
  restore_deps:
    steps:
      - run:
          name: "ELIXIR_VERSION.lock"
          command: echo "${ELIXIR_VERSION}" > ELIXIR_VERSION.lock
      - run:
          name: "OTP_VERSION.lock"
          command: echo "${OTP_VERSION}" > OTP_VERSION.lock
      - restore_cache:
          keys:
            - v8-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.lock" }}
            - v8-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.exs" }}
            - v8-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
  save_deps:
    steps:
      - run:
          name: "ELIXIR_VERSION.lock"
          command: echo "${ELIXIR_VERSION}" > ELIXIR_VERSION.lock
      - run:
          name: "OTP_VERSION.lock"
          command: echo "${OTP_VERSION}" > OTP_VERSION.lock
      - save_cache:
          key: v8-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.lock" }}
          paths:
            - deps
            - _build
            - ~/.mix
            - priv/plts
      - save_cache:
          key: v8-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.exs" }}
          paths:
            - deps
            - _build
            - ~/.mix
            - priv/plts
      - save_cache:
          key: v8-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - deps
            - _build
            - ~/.mix
            - priv/plts
  wait_for_postgres:
    steps:
      - setup_remote_docker
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
  setup-sccache:
    steps:
      - run:
          name: Install sccache
          command: |
            cargo install sccache
            # This configures Rust to use sccache.
            echo 'export "RUSTC_WRAPPER"="sccache"' >> $BASH_ENV
            # This is the maximum space sccache cache will use on disk.
            echo 'export "SCCACHE_CACHE_SIZE"="1G"' >> $BASH_ENV
            sccache --version
  restore-sccache-cache:
    steps:
      - restore_cache:
          name: Restore sccache cache
          key: v1-sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
  save-sccache-cache:
    steps:
      - save_cache:
          name: Save sccache cache
          # We use {{ epoch }} to always upload a fresh cache:
          # Of course, restore_cache will not find this exact key,
          # but it will fall back to the closest key (aka the most recent).
          # See https://discuss.circleci.com/t/add-mechanism-to-update-existing-cache-key/9014/13
          key: v1-sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths:
            - "~/.cache/sccache"
  start_server:
    steps:
      - restore_deps
      - run: cd ~/app/server && mix phx.server

jobs:
  checkout_code:
    executor:
      name: elixir
    steps:
      - checkout
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - app
  server_mix_deps:
    executor:
      name: elixir
      app: "server"
    steps:
      - fast-checkout
      - restore_deps
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, deps.compile, compile
      - save_deps
  server_test:
    executor:
      name: elixir
      app: "server"
    steps:
      - fast-checkout
      - restore_deps
      - wait_for_postgres
      - run: mix ecto.setup
      - run: mkdir -p /tmp/server_junit/
      - run: mix coveralls.json
      - run: bash <(curl -s https://codecov.io/bash)
      - run: mix test --formatter JUnitFormatter
      - store_test_results:
          path: /tmp/server_junit
      - store_artifacts:
          path: /tmp/server_junit
  server_quality_check:
    executor:
      name: elixir
      app: "server"
    steps:
      - fast-checkout
      - restore_deps
      - run:
          name: Credo
          command: mix credo --strict --ignore todo
  server_format_check:
    executor:
      name: elixir
      app: "server"
    steps:
      - fast-checkout
      - restore_deps
      - run: mix format
      - save_deps
  server_dialyzer:
    executor:
      name: elixir
      app: "server"
    steps:
      - fast-checkout
      - restore_deps
      - restore_plts
      - run: mkdir -p priv/plts
      - run: mix dialyzer --halt-exit-status --format short
      - save_plts
  cli_generate_lockfile:
    executor:
      name: elixir
      app: "cli"
    steps:
      - run:
          name: Calculate dependencies
          command: test -e Cargo.lock || cargo generate-lockfile
  cli_build:
    executor:
      name: elixir
      app: "cli"
    steps:
      - fast-checkout
      - run: cargo install --path .
      - setup-sccache
      - restore-sccache-cache
      - run: cargo build
      - save-sccache-cache
  cli_test:
    executor:
      name: elixir
      app: "cli"
    steps:
      - fast-checkout
      - setup-sccache
      - restore-sccache-cache
      - start_server
      - run: cargo test --all
      - save-sccache-cache
  cli_format:
    executor:
      name: elixir
      app: "cli"
    steps:
      - cli_generate_lockfile
      - run:
          name: Check formatting
          command: |
            if rustup component add rustfmt; then
              cargo fmt --all -- --check
            else
              echo Skipping rustfmt
            fi

workflows:
  version: 2
  server_build_and_test:
    jobs:
      - checkout_code
      - server_mix_deps:
          requires:
            - checkout_code
      - server_test:
          requires:
            - server_mix_deps
      - server_format_check:
          requires:
            - server_mix_deps
      - server_quality_check:
          requires:
            - server_mix_deps
      - server_dialyzer:
          requires:
            - server_mix_deps
      - cli_build:
          requires:
            - checkout_code
      - cli_test:
          requires:
            - server_mix_deps
            - cli_build
