#![allow(unknown_lints)]
#![warn(clippy)]
[package]
name = "buffcli"
version = "0.1.0"
authors = ["BlueHotDog <BlueHotDog@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"

[dev-dependencies]
assert_cmd = "0.11.1"
rexpect = "0.3.0"
