version: "2"
services:
 minio:
  image: minio/minio:latest
  volumes:
   - minio-data:/data
  ports:
   - "9000:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server /data
## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio-data:
