version: '2'

# note(itay): Minio requires a minimum of 4 server instances
# 
# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
 minio:
  image: minio/minio:latest
  volumes:
   - minio-data:/data
  ports:
   - "9000:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server /data
## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio-data:
